import { ArrowLeft, ArrowRight, Check, CircleHelp, GraduationCap } from "lucide-react";
import { useState } from "react";
import { useSearchParams } from "react-router-dom";
import { SubmitArea } from "../components/FormStatus";
import { PageHero } from "../components/UI";
import { courses } from "../data/catalog";
import useDemoSubmit from "../hooks/useDemoSubmit";

const steps = ["Student Information", "Current Studies", "Courses of Interest", "Academic Goal", "Contact Preferences", "Review & Submit"];

export default function InquiryPage() {
  const [params] = useSearchParams();
  const [step, setStep] = useState(0);
  const [form, setForm] = useState({ course: params.get("course") || "", isAdult: "", international: "", unsure: false, contact: "Email" });
  const submit = useDemoSubmit();
  const set = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.type === "checkbox" ? event.target.checked : event.target.value }));
  const next = () => setStep((current) => Math.min(current + 1, steps.length - 1));
  const previous = () => setStep((current) => Math.max(current - 1, 0));

  return (
    <>
      <PageHero eyebrow="START AN INQUIRY" title="Tell Us What You’re Working Toward." text="Share your current studies, course interests and academic goal through a clear six-step inquiry." />
      <section className="section container inquiry-layout">
        <aside className="inquiry-sidebar"><span className="mini-label">YOUR PROGRESS</span><ol>{steps.map((label, index) => <li className={index === step ? "active" : index < step ? "complete" : ""} key={label}><button type="button" onClick={() => index < step && setStep(index)} aria-current={index === step ? "step" : undefined}><span>{index < step ? <Check size={15} /> : index + 1}</span><strong>{label}</strong></button></li>)}</ol><div className="inquiry-help"><CircleHelp size={22} /><strong>Not sure where to begin?</strong><span>You can tell us the goal even if you do not know the exact course code.</span></div></aside>
        <form className="form-card inquiry-form" onSubmit={submit.onSubmit}>
          <div className="mobile-progress"><span>Step {step + 1} of {steps.length}</span><strong>{steps[step]}</strong><div><span style={{ width: `${((step + 1) / steps.length) * 100}%` }} /></div></div>
          <div className="form-heading"><span className="mini-label">STEP {step + 1}</span><h2>{steps[step]}</h2></div>
          {step === 0 && <div className="form-grid"><label>First name<input value={form.first || ""} onChange={set("first")} required autoComplete="given-name" /></label><label>Last name<input value={form.last || ""} onChange={set("last")} required autoComplete="family-name" /></label><label>Email<input value={form.email || ""} onChange={set("email")} required type="email" autoComplete="email" /></label><label>Phone<input value={form.phone || ""} onChange={set("phone")} type="tel" autoComplete="tel" /></label><label>Date of birth<input value={form.dob || ""} onChange={set("dob")} type="date" /></label><label>Are you 18 or older?<select value={form.isAdult} onChange={set("isAdult")} required><option value="">Select one</option><option value="yes">Yes</option><option value="no">No</option></select></label>{form.isAdult === "no" && <><label>Parent / guardian name<input value={form.guardian || ""} onChange={set("guardian")} required /></label><label>Parent / guardian email<input value={form.guardianEmail || ""} onChange={set("guardianEmail")} required type="email" /></label></>}</div>}
          {step === 1 && <div className="form-grid"><label>Current grade<select value={form.grade || ""} onChange={set("grade")} required><option value="">Select grade</option>{[9,10,11,12].map((grade) => <option key={grade}>{grade}</option>)}<option>Not currently enrolled</option></select></label><label>International student?<select value={form.international} onChange={set("international")} required><option value="">Select one</option><option value="yes">Yes</option><option value="no">No</option></select></label><label>City<input value={form.city || ""} onChange={set("city")} autoComplete="address-level2" /></label><label>Province / state<input value={form.province || ""} onChange={set("province")} autoComplete="address-level1" /></label><label>Country<input value={form.country || "Canada"} onChange={set("country")} autoComplete="country-name" /></label><label>Current / previous school<input value={form.school || ""} onChange={set("school")} /></label><label className="field-wide">Ontario high-school history<textarea value={form.history || ""} onChange={set("history")} rows="4" placeholder="Share relevant credits, courses or Ontario school history." /></label></div>}
          {step === 2 && <div className="form-grid"><label className="field-wide">Search course catalogue<input list="course-options" value={form.course} onChange={set("course")} placeholder="Start typing a course code or title" /><datalist id="course-options">{courses.map((course) => <option value={`${course.code} — ${course.title}`} key={course.code} />)}</datalist></label><label className="check-control field-wide"><input type="checkbox" checked={form.unsure} onChange={set("unsure")} /><span>I’m not sure which course I need.</span></label>{form.unsure && <label className="field-wide">What guidance would help?<textarea value={form.guidance || ""} onChange={set("guidance")} rows="5" placeholder="Tell us the subject, credit, prerequisite or goal you are trying to address." /></label>}<label className="field-wide">Other courses of interest<textarea value={form.otherCourses || ""} onChange={set("otherCourses")} rows="4" /></label></div>}
          {step === 3 && <div className="form-grid"><label className="field-wide">Academic goal<select value={form.goal || ""} onChange={set("goal")} required><option value="">Select a goal</option><option>Complete a credit</option><option>Meet a prerequisite</option><option>Prepare for university</option><option>Prepare for college</option><option>Upgrade a course</option><option>Explore a subject or career</option><option>Other</option></select></label><label className="field-wide">Postsecondary goal<textarea value={form.postsecondary || ""} onChange={set("postsecondary")} rows="4" placeholder="Program, field or pathway if known" /></label><label>Preferred deadline<input value={form.deadline || ""} onChange={set("deadline")} type="date" /></label><label>Timing notes<input value={form.timing || ""} onChange={set("timing")} placeholder="Any important timing context" /></label></div>}
          {step === 4 && <div className="form-grid"><label>Preferred contact method<select value={form.contact} onChange={set("contact")}><option>Email</option><option>Phone</option></select></label><label>Best time to contact<select value={form.contactTime || ""} onChange={set("contactTime")}><option value="">No preference</option><option>Morning</option><option>Afternoon</option><option>Evening</option></select></label><label className="field-wide">Anything else we should know?<textarea value={form.notes || ""} onChange={set("notes")} rows="5" /></label></div>}
          {step === 5 && <div className="review-inquiry"><div><span>Student</span><strong>{[form.first, form.last].filter(Boolean).join(" ") || "Not provided"}</strong><small>{form.email || "Email not provided"}</small></div><div><span>Current studies</span><strong>{form.grade ? `Grade ${form.grade}` : "Not provided"}</strong><small>{form.school || "School not provided"}</small></div><div><span>Course interest</span><strong>{form.unsure ? "Guidance requested" : form.course || "Not provided"}</strong><small>{form.otherCourses || "No additional courses"}</small></div><div><span>Academic goal</span><strong>{form.goal || "Not provided"}</strong><small>{form.deadline || "No deadline provided"}</small></div><label className="check-control field-wide"><input required type="checkbox" /><span>I consent to Nexus contacting me about this inquiry and confirm the information is appropriate to submit.</span></label></div>}
          <div className="inquiry-actions">{step > 0 && <button className="btn btn-secondary" type="button" onClick={previous}><ArrowLeft size={16} /> Back</button>}<span />{step < steps.length - 1 ? <button className="btn btn-primary" type="button" onClick={next}>Continue <ArrowRight size={16} /></button> : <SubmitArea submitted={submit.submitted} label="Send Inquiry" />}</div>
        </form>
      </section>
    </>
  );
}
